# Generated by Django 3.1.7 on 2021-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.DecimalField(blank=True, decimal_places=15, help_text='Filling in Longitude', max_digits=20)),
                ('Y', models.DecimalField(blank=True, decimal_places=15, help_text='Filling in Latitude', max_digits=20)),
                ('Unique_squirrel_ID', models.CharField(help_text='Unique ID for squirrel number', max_length=20, primary_key=True, serialize=False)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Choose from AM or PM', max_length=20)),
                ('Date', models.DateField(help_text='Filling in date when squirrel was spotted')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Choose age from adult or juvenile', max_length=20)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Choose color form gray, cinnamon or black', max_length=20)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Choose location from ground plane or above ground', max_length=20)),
                ('Specific_Location', models.CharField(blank=True, help_text='Additional information for the squirrel location', max_length=20)),
                ('Running', models.BooleanField(default=False, help_text='Select if squirrel was running')),
                ('Chasing', models.BooleanField(default=False, help_text='Select if squirrel was chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Select if squirrel was climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Select if squirrel was eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Select if squirrel was foraging')),
                ('Other_Activities', models.TextField(blank=True, help_text='Filling in other activity by squirrel')),
                ('Kuks', models.BooleanField(default=False, help_text='Select if squirrel was kuking')),
                ('Quaas', models.BooleanField(default=False, help_text='Select if squirrel was quaaing')),
                ('Moans', models.BooleanField(default=False, help_text='Select if squirrel was moaning')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Select if squirrel was flagging tail')),
                ('Tail_twitching', models.BooleanField(default=False, help_text='Select if squirrel was twitching tail')),
                ('Approaches', models.BooleanField(default=False, help_text='Select if squirrel was approaching human')),
                ('Indifferent', models.BooleanField(default=False, help_text='Select if squirrel was indifferent to human')),
                ('Runs_from', models.BooleanField(default=False, help_text='Select if squirrel was running from human')),
            ],
        ),
    ]
